# libsaithrift-dev package

LIBSAITHRIFT_DEV_BFN = libsaithrift-dev_0.9.4_amd64.deb
$(LIBSAITHRIFT_DEV_BFN)_SRC_PATH = $(SRC_PATH)/SAI
$(LIBSAITHRIFT_DEV_BFN)_DEPENDS += $(LIBTHRIFT) $(LIBTHRIFT_DEV) $(THRIFT_COMPILER) $(BFN_SAI) $(BFN_SAI_DEV)
$(LIBSAITHRIFT_DEV_BFN)_RDEPENDS += $(LIBTHRIFT) $(BFN_SAI)
#SONIC_DPKG_DEBS += $(LIBSAITHRIFT_DEV_BFN)
