# BFN Platform modules

BFN_PLATFORM_MODULE_VERSION = 1.0

export BFN_PLATFORM_MODULE_VERSION

BFN_PLATFORM_MODULE = platform-modules-bfn_$(BFN_PLATFORM_MODULE_VERSION)_amd64.deb
$(BFN_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-bfn
$(BFN_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BFN_PLATFORM_MODULE)_PLATFORM = x86_64-accton_wedge100bf_65x-r0
SONIC_DPKG_DEBS += $(BFN_PLATFORM_MODULE)
