# Netberg tofino-based platforms modules

NETBERG_AURORA_610_PLATFORM_MODULE_VERSION = 1.1.1
NETBERG_AURORA_710_PLATFORM_MODULE_VERSION = 1.1.1
NETBERG_AURORA_750_PLATFORM_MODULE_VERSION = 1.1.1

export NETBERG_AURORA_610_PLATFORM_MODULE_VERSION
export NETBERG_AURORA_710_PLATFORM_MODULE_VERSION
export NETBERG_AURORA_750_PLATFORM_MODULE_VERSION

NETBERG_AURORA_610_PLATFORM_MODULE = sonic-platform-netberg-aurora-610_$(NETBERG_AURORA_610_PLATFORM_MODULE_VERSION)_amd64.deb
$(NETBERG_AURORA_610_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-netberg
$(NETBERG_AURORA_610_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(NETBERG_AURORA_610_PLATFORM_MODULE)_PLATFORM = x86_64-netberg_aurora_610-r0

SONIC_DPKG_DEBS += $(NETBERG_AURORA_610_PLATFORM_MODULE)

NETBERG_AURORA_710_PLATFORM_MODULE = sonic-platform-netberg-aurora-710_$(NETBERG_AURORA_710_PLATFORM_MODULE_VERSION)_amd64.deb
$(NETBERG_AURORA_710_PLATFORM_MODULE)_PLATFORM = x86_64-netberg_aurora_710-r0

$(eval $(call add_extra_package,$(NETBERG_AURORA_610_PLATFORM_MODULE),$(NETBERG_AURORA_710_PLATFORM_MODULE)))

NETBERG_AURORA_750_PLATFORM_MODULE = sonic-platform-netberg-aurora-750_$(NETBERG_AURORA_750_PLATFORM_MODULE_VERSION)_amd64.deb
$(NETBERG_AURORA_750_PLATFORM_MODULE)_PLATFORM = x86_64-netberg_aurora_750-r0

$(eval $(call add_extra_package,$(NETBERG_AURORA_610_PLATFORM_MODULE),$(NETBERG_AURORA_750_PLATFORM_MODULE)))
