# BFN Platform modules

BFN_MONTARA_PLATFORM_MODULE_VERSION = 1.1

export BFN_MONTARA_PLATFORM_MODULE_VERSION

BFN_MONTARA_PLATFORM_MODULE = sonic-platform-modules-bfn-montara_$(BFN_MONTARA_PLATFORM_MODULE_VERSION)_amd64.deb
$(BFN_MONTARA_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-bfn-montara
$(BFN_MONTARA_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BFN_MONTARA_PLATFORM_MODULE)_PLATFORM = x86_64-accton_wedge100bf_32x-r0
SONIC_DPKG_DEBS += $(BFN_MONTARA_PLATFORM_MODULE)
