#!/bin/bash

function check_not_installed()
{
  c=0
  config=$(vtysh -c "show run")
  for route_map_name in $(echo "$config" | sed -ne 's/  neighbor \S* route-map \(\S*\) out/\1/p');
  do
    echo "$config" | grep -q "route-map $route_map_name permit 2"
    c=$((c+$?))
    echo "$config" | grep -q "route-map $route_map_name deny 3"
    c=$((c+$?))
  done
  return $c
}

function check_installed()
{
  c=0
  e=0
  config=$(vtysh -c "show run")
  for route_map_name in $(echo "$config" | sed -ne 's/  neighbor \S* route-map \(\S*\) out/\1/p');
  do
    echo "$config" | grep -q "route-map $route_map_name permit 2"
    c=$((c+$?))
    e=$((e+1))
    echo "$config" | grep -q "route-map $route_map_name deny 3"
    c=$((c+$?))
    e=$((e+1))
  done
  return $((e-c))
}

echo "Traffic Shift Check:"

check_not_installed
not_installed=$?

check_installed
installed=$?

if [[ $installed -eq 0 ]];
then
  echo "System Mode: Normal"
elif [[ $not_installed -eq 0 ]];
then
  echo "System Mode: Maintenance"
else
  echo "System Mode: Not consistent"
fi

echo
