obj-m := x86-64-netberg-aurora-715.o
x86-64-netberg-aurora-715-objs := x86-64-netberg-aurora-715-common.o x86-64-netberg-aurora-715-sys.o \
x86-64-netberg-aurora-715-led.o x86-64-netberg-aurora-715-fan.o x86-64-netberg-aurora-715-power.o \
x86-64-netberg-aurora-715-thermal.o x86-64-netberg-aurora-715-qsfp.o
