{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files, cleanup_apt_and_python_cache %}
FROM docker-config-engine-buster-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name
RUN [ -f /etc/rsyslog.conf ] && sed -ri "s/%syslogtag%/$docker_container_name#%syslogtag%/;" /etc/rsyslog.conf

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y g++ python3-dev libxml2 libcurl3-gnutls libcjson-dev

RUN pip3 install connexion==2.7.0 \
                 setuptools==21.0.0 \
                 grpcio-tools==1.20.0 \
                 certifi==2017.4.17 \
                 python-dateutil==2.6.0 \
                 six==1.11.0 \
                 urllib3==1.26.5

# Copy locally-built Debian package dependencies
{{ copy_files("debs/", docker_sonic_mgmt_framework_debs.split(' '), "/debs/") }}

# Install locally-built Debian packages and implicitly install their dependencies
{{ install_debian_packages(docker_sonic_mgmt_framework_debs.split(' ')) }}

COPY ["start.sh", "rest-server.sh", "/usr/bin/"]
COPY ["mgmt_vars.j2", "/usr/share/sonic/templates/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

RUN apt-get remove -y g++ python3-dev
{{ cleanup_apt_and_python_cache() }}

ENTRYPOINT ["/usr/local/bin/supervisord"]
