obj-m := fpga_device.o fpga_system.o i2c_switchcpld.o fpga_i2c_ocores.o fpga_xcvr.o lpc_basecpld.o mc24lc64t.o optoe.o mcp3425_smbus.o mp2975.o platform_fan.o platform_psu.o tps536c7.o ucd90120.o ucd90160.o


