ccflags-y := -Werror

#ifeq ($(ARISTA_SCD_DRIVER_CONFIG),m)
#obj-$(ARISTA_SCD_DRIVER_CONFIG) += scd.o
#else
#KBUILD_EXTRA_SYMBOLS += $(EXTRA_SYMBOLS)
#endif

#obj-m += scd-hwmon.o
#obj-m += crow-fan-driver.o
#obj-m += raven-fan-driver.o
#obj-m += rook-led-driver.o
#obj-m += rook-fan-cpld.o
