es9618xx/sonic_platform-1.0-py3-none-any.whl usr/share/sonic/device/x86_64-accton_es9618xx-r0
es9618xx/files/link/70-xsight-eth10g0.link usr/lib/systemd/network
es9618xx/files/link/70-xsight-eth10g1.link usr/lib/systemd/network
es9618xx/files/link/70-xsight-eth10g2.link usr/lib/systemd/network
es9618xx/files/link/70-xsight-eth10g3.link usr/lib/systemd/network
es9618xx/files/link/70-xsight-eth1g0.link usr/lib/systemd/network
es9618xx/files/link/70-xsight-eth1g1.link usr/lib/systemd/network
