as9647-32d/sonic_platform-1.0-py3-none-any.whl usr/share/sonic/device/x86_64-accton_as9647_32d-r0
as9647-32d/files/link/70-xsight-eth10g0.link usr/lib/systemd/network
as9647-32d/files/link/70-xsight-eth10g1.link usr/lib/systemd/network
as9647-32d/files/link/70-xsight-eth10g2.link usr/lib/systemd/network
as9647-32d/files/link/70-xsight-eth10g3.link usr/lib/systemd/network
as9647-32d/files/link/70-xsight-eth1g0.link usr/lib/systemd/network
as9647-32d/files/link/70-xsight-eth1g1.link usr/lib/systemd/network
