#
# BCM56880 32x400g port configuration.
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#
# $Copyright: (c) 2019 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

---
bcm_device:
    0:
        global:
            bcm_tunnel_term_compatible_mode: 1
            # Multicast group allocated by brcm-sai, setting "vlan_flooding_l2mc_num_reserved=0" 
            vlan_flooding_l2mc_num_reserved: 0
            shared_block_mask_section: uc_bc
            sai_tunnel_support: 1
            l3_alpm_template: 1
            l3_alpm2_bnk_threshold: 100
            uft_mode: 1
            l3_enable: 1
            l2_hitbit_enable: 1
            pktio_mode: 1
            skip_protocol_default_entries: 1
            ifa_enable: 1
...
---
device:
  0:
    DEVICE_CONFIG:
      # CORE CLOCK FREQUENCY
      CORE_CLK_FREQ: CLK_1350MHZ
      # PP CLOCK FREQUENCY
      PP_CLK_FREQ: CLK_1350MHZ
...
---
device:
  0:
    PC_PM_CORE:
      ?
        PC_PM_ID: 1
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x01476352
        TX_LANE_MAP: 0x67015324
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0xDD
      ?
        PC_PM_ID: 2
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x21563047
        TX_LANE_MAP: 0x70146253
        RX_POLARITY_FLIP: 0xEF
        TX_POLARITY_FLIP: 0x6
      ?
        PC_PM_ID: 3
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x34216570
        TX_LANE_MAP: 0x02453617
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0xEE
      ?
        PC_PM_ID: 4
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x26531470
        TX_LANE_MAP: 0x40726513
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0xBE
      ?
        PC_PM_ID: 5
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x23641705
        TX_LANE_MAP: 0x45326071
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0xB3
      ?
        PC_PM_ID: 6
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x45013726
        TX_LANE_MAP: 0x23170564
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0x21
      ?
        PC_PM_ID: 7
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x41025763
        TX_LANE_MAP: 0x25674013
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0x4
      ?
        PC_PM_ID: 8
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x01675243
        TX_LANE_MAP: 0x07236415
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0xEB
      ?
        PC_PM_ID: 9
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x56024713
        TX_LANE_MAP: 0x21670534
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0x3E
      ?
        PC_PM_ID: 10
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x01675342
        TX_LANE_MAP: 0x43607512
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0x3D
      ?
        PC_PM_ID: 11
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x20563147
        TX_LANE_MAP: 0x50126734
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0xF3
      ?
        PC_PM_ID: 12
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x46150723
        TX_LANE_MAP: 0x13456072
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0xEA
      ?
        PC_PM_ID: 13
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x51276034
        TX_LANE_MAP: 0x35476012
        RX_POLARITY_FLIP: 0xC5
        TX_POLARITY_FLIP: 0xED
      ?
        PC_PM_ID: 14
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x65217430
        TX_LANE_MAP: 0x02541637
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0x4
      ?
        PC_PM_ID: 15
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x32461057
        TX_LANE_MAP: 0x54107362
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0xCD
      ?
        PC_PM_ID: 16
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x31405267
        TX_LANE_MAP: 0x63150724
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0xF4
      ?
        PC_PM_ID: 17
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x01475263
        TX_LANE_MAP: 0x63017524
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0xFF
      ?
        PC_PM_ID: 18
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x21463057
        TX_LANE_MAP: 0x70135462
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0x9C
      ?
        PC_PM_ID: 19
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x64217530
        TX_LANE_MAP: 0x23561407
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0x53
      ?
        PC_PM_ID: 20
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x10652473
        TX_LANE_MAP: 0x25306417
        RX_POLARITY_FLIP: 0x14
        TX_POLARITY_FLIP: 0xCA
      ?
        PC_PM_ID: 21
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x24561307
        TX_LANE_MAP: 0x65407321
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0x37
      ?
        PC_PM_ID: 22
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x27416350
        TX_LANE_MAP: 0x06573421
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0xFB
      ?
        PC_PM_ID: 23
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x40517263
        TX_LANE_MAP: 0x30742516
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0xB1
      ?
        PC_PM_ID: 24
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x02561347
        TX_LANE_MAP: 0x53017624
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0x23
      ?
        PC_PM_ID: 25
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x64127503
        TX_LANE_MAP: 0x40572613
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0xC
      ?
        PC_PM_ID: 26
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x01475362
        TX_LANE_MAP: 0x67015324
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0x5C
      ?
        PC_PM_ID: 27
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x46150723
        TX_LANE_MAP: 0x21630754
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0xA0
      ?
        PC_PM_ID: 28
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x20563147
        TX_LANE_MAP: 0x23607451
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0xCF
      ?
        PC_PM_ID: 29
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x72541360
        TX_LANE_MAP: 0x50461237
        RX_POLARITY_FLIP: 0x22
        TX_POLARITY_FLIP: 0x15
      ?
        PC_PM_ID: 30
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x32465071
        TX_LANE_MAP: 0x64312705
        RX_POLARITY_FLIP: 0xFF
        TX_POLARITY_FLIP: 0x7F
      ?
        PC_PM_ID: 31
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x56412730
        TX_LANE_MAP: 0x31647250
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0x20
      ?
        PC_PM_ID: 32
        CORE_INDEX: 0
      :
        RX_LANE_MAP_AUTO: 0
        TX_LANE_MAP_AUTO: 0
        RX_POLARITY_FLIP_AUTO: 0
        TX_POLARITY_FLIP_AUTO: 0
        RX_LANE_MAP: 0x64127503
        TX_LANE_MAP: 0x54321607
        RX_POLARITY_FLIP: 0x0
        TX_POLARITY_FLIP: 0x80
...
---
device:
  0:
    PC_PORT_PHYS_MAP:
      ?
        # CPU port
        PORT_ID: 0
      :
        PC_PHYS_PORT_ID: 0
      ?
        PORT_ID: 1
      :
        PC_PHYS_PORT_ID: 1 #TSC-BH7 0 in Pipe 0
      ?
        PORT_ID: 2
      :
        PC_PHYS_PORT_ID: 9 #TSC-BH7 1 in Pipe 0
      ?
        PORT_ID: 3
      :
        PC_PHYS_PORT_ID: 17 #TSC-BH7 2 in Pipe 0
      ?
        PORT_ID: 4
      :
        PC_PHYS_PORT_ID: 25 #TSC-BH7 3 in Pipe 0
      ?
        PORT_ID: 20
      :
        PC_PHYS_PORT_ID: 33 #TSC-BH7 4 in Pipe 1
      ?
        PORT_ID: 21
      :
        PC_PHYS_PORT_ID: 41 #TSC-BH7 5 in Pipe 1
      ?
        PORT_ID: 22
      :
        PC_PHYS_PORT_ID: 49 #TSC-BH7 6 in Pipe 1
      ?
        PORT_ID: 23
      :
        PC_PHYS_PORT_ID: 57 #TSC-BH7 7 in Pipe 1
      ?
        PORT_ID: 40
      :
        PC_PHYS_PORT_ID: 65 #TSC-BH7 8 in Pipe 2
      ?
        PORT_ID: 41
      :
        PC_PHYS_PORT_ID: 73 #TSC-BH7 9 in Pipe 2
      ?
        PORT_ID: 42
      :
        PC_PHYS_PORT_ID: 81 #TSC-BH7 10 in Pipe 2
      ?
        PORT_ID: 43
      :
        PC_PHYS_PORT_ID: 89 #TSC-BH7 11 in Pipe 2
      ?
        PORT_ID: 60
      :
        PC_PHYS_PORT_ID: 97 #TSC-BH7 12 in Pipe 3
      ?
        PORT_ID: 61
      :
        PC_PHYS_PORT_ID: 105 #TSC-BH7 13 in Pipe 3
      ?
        PORT_ID: 62
      :
        PC_PHYS_PORT_ID: 113 #TSC-BH7 14 in Pipe 3
      ?
        PORT_ID: 63
      :
        PC_PHYS_PORT_ID: 121 #TSC-BH7 15 in Pipe 3
      ?
        PORT_ID: 80
      :
        PC_PHYS_PORT_ID: 129 #TSC-BH7 16 in Pipe 4
      ?
        PORT_ID: 81
      :
        PC_PHYS_PORT_ID: 137 #TSC-BH7 17 in Pipe 4
      ?
        PORT_ID: 82
      :
        PC_PHYS_PORT_ID: 145 #TSC-BH7 18 in Pipe 4
      ?
        PORT_ID: 83
      :
        PC_PHYS_PORT_ID: 153 #TSC-BH7 19 in Pipe 4
      ?
        PORT_ID: 100
      :
        PC_PHYS_PORT_ID: 161 #TSC-BH7 20 in Pipe 5
      ?
        PORT_ID: 101
      :
        PC_PHYS_PORT_ID: 169 #TSC-BH7 21 in Pipe 5
      ?
        PORT_ID: 102
      :
        PC_PHYS_PORT_ID: 177 #TSC-BH7 22 in Pipe 5
      ?
        PORT_ID: 103
      :
        PC_PHYS_PORT_ID: 185 #TSC-BH7 23 in Pipe 5
      ?
        PORT_ID: 120
      :
        PC_PHYS_PORT_ID: 193 #TSC-BH7 24 in Pipe 6
      ?
        PORT_ID: 121
      :
        PC_PHYS_PORT_ID: 201 #TSC-BH7 25 in Pipe 6
      ?
        PORT_ID: 122
      :
        PC_PHYS_PORT_ID: 209 #TSC-BH7 26 in Pipe 6
      ?
        PORT_ID: 123
      :
        PC_PHYS_PORT_ID: 217 #TSC-BH7 27 in Pipe 6
      ?
        PORT_ID: 140
      :
        PC_PHYS_PORT_ID: 225 #TSC-BH7 28 in Pipe 7
      ?
        PORT_ID: 141
      :
        PC_PHYS_PORT_ID: 233 #TSC-BH7 29 in Pipe 7
      ?
        PORT_ID: 142
      :
        PC_PHYS_PORT_ID: 241 #TSC-BH7 30 in Pipe 7
      ?
        PORT_ID: 143
      :
        PC_PHYS_PORT_ID: 249 #TSC-BH7 31 in Pipe 7
      #?
        # Management port 0 (Pipe 1) - CPU
      #  PORT_ID: 38
      #:
      #  PC_PHYS_PORT_ID: 257
      #?
        # Management port 1 (Pipe 3) - CPU
      #  PORT_ID: 78
      #:
      #  PC_PHYS_PORT_ID: 258
      ?
        # Management port 2 (Pipe 5) - Front Panel Port
        PORT_ID: 118
      :
        PC_PHYS_PORT_ID: 259
      ?
        # Management port 3 (Pipe 7) - Front Panel Port
        PORT_ID: 158
      :
        PC_PHYS_PORT_ID: 260
...
---
device:
  0:
    PC_PORT:
      ?
        PORT_ID: 0
      :
        &port_mode_10g
        ENABLE: 1
        SPEED: 10000
        NUM_LANES: 1
      ?
        PORT_ID: [[1, 4],
                 [20, 23],
                 [40, 43],
                 [60, 63],
                 [80, 83],
                 [100, 103],
                 [120, 123],
                 [140, 143]]
      :
        &port_mode_400g
        ENABLE: 0
        SPEED: 400000
        NUM_LANES: 8
        FEC_MODE: PC_FEC_RS544_2XN
        MAX_FRAME_SIZE: 9416
        #LINK_TRAINING: 1
      #?
      #  PORT_ID: [38,   # Management port 0 (Pipe 1) - CPU
      #            78]   # Management port 1 (Pipe 3) - CPU
      #:
      #  &port_mode_10g_xfi
      #  ENABLE: 0
      #  SPEED: 10000
      #  NUM_LANES: 1
      #  MAX_FRAME_SIZE: 9416
      ?
        PORT_ID: [118,  # Management port 2 (Pipe 5) - Front Panel Port
                  158]  # Management port 3 (Pipe 7) - Front Panel Port
      :
        &port_mode_10g_xfi
        ENABLE: 0
        SPEED: 10000
        NUM_LANES: 1
        MAX_FRAME_SIZE: 9416

    PC_PMD_FIRMWARE:
      ?
        PORT_ID: [[1, 4],
                 [20, 23],
                 [40, 43],
                 [60, 63],
                 [80, 83],
                 [100, 103],
                 [120, 123],
                 [140, 143]]
      :
        MEDIUM_TYPE_AUTO: 0
        MEDIUM_TYPE: PC_PHY_MEDIUM_COPPER
...
---
device:
    0:
        TM_SCHEDULER_CONFIG:
            NUM_MC_Q: NUM_MC_Q_4
...
---
device:
    0:
        FP_CONFIG:
            FP_ING_OPERMODE: GLOBAL_PIPE_AWARE
...
