obj-m:=mitac_ly1200_32x_fb_i2c.o mitac_ly1200_32x_fse000.o \
mitac_ly1200_32x_master_cpld.o mitac_ly1200_32x_sb_i2c.o \
mitac_ly1200_32x_system_cpld.o mitac_ly1200_32x_cb_i2c.o \
mitac_ly1200_32x_fb_module_i2c.o mitac_ly1200_32x_gpe.o \
mitac_ly1200_32x_pb_i2c.o mitac_ly1200_32x_slave_cpld.o
