# embedway es6220 Platform modules

EMBEDWAY_ES6220_PLATFORM_MODULE_VERSION =1.1

export EMBEDWAY_ES6220_PLATFORM_MODULE_VERSION

EMBEDWAY_ES6220_PLATFORM_MODULE = platform-modules-embedway-es6220_$(EMBEDWAY_ES6220_PLATFORM_MODULE_VERSION)_amd64.deb

$(EMBEDWAY_ES6220_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-embedway
$(EMBEDWAY_ES6220_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(EMBEDWAY_ES6220_PLATFORM_MODULE)_PLATFORM = x86_64-ew_es6220_x48q2h4-r0
SONIC_STRETCH_DEBS += $(EMBEDWAY_ES6220_PLATFORM_MODULE)
SONIC_DPKG_DEBS += $(EMBEDWAY_ES6220_PLATFORM_MODULE)