# Pegatron Platform modules

PEGATRON_PORSCHE_PLATFORM_MODULE_VERSION = 0.1

export PEGATRON_PORSCHE_PLATFORM_MODULE_VERSION

PEGATRON_PORSCHE_PLATFORM_MODULE = sonic-platform-pegatron-porsche_$(PEGATRON_PORSCHE_PLATFORM_MODULE_VERSION)_amd64.deb
$(PEGATRON_PORSCHE_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-pegatron
$(PEGATRON_PORSCHE_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(PEGATRON_PORSCHE_PLATFORM_MODULE)_PLATFORM = x86_64-pegatron_porsche-r0
SONIC_DPKG_DEBS += $(PEGATRON_PORSCHE_PLATFORM_MODULE)

$(eval $(call add_extra_package,$(PEGATRON_PORSCHE_PLATFORM_MODULE)))
