#!/bin/bash -e

usage(){
   echo "Usage:   $0 <shutdown|startup> <neighbor_ip>"
   exit 255
}

[[ $# -ne 2 ]] && usage

COMMAND=$1
NEIGHBOR_IP=$2

if [ "$COMMAND" == "shutdown" ]; then
    CMD_PREFIX=""
elif [ "$COMMAND" == "startup" ]; then
    CMD_PREFIX="no"
else
    usage
fi

ASN=`vtysh -c "show ip bgp summary" | sed -n "s/.*AS number \([0-9]\+\).*/\1/p"`
if [ -z "$ASN" ]; then
    exit 255
fi

[ -f /etc/sonic/bgp_admin.yml ] || echo "bgp_admin_state:" > /etc/sonic/bgp_admin.yml

# Operate on all ipv4 neighbors when "neighbor_ip" = 0.0.0.0
if [ "$NEIGHBOR_IP" == "0.0.0.0" ] ; then
    for NEIGHBOR in `vtysh -c "show run" | grep nei | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | sort | uniq`; do
        vtysh -c "configure terminal" -c "router bgp $ASN" -c "$CMD_PREFIX neighbor $NEIGHBOR shutdown"
        
        # Save admin state in config file
        sed -i "/^\s*$NEIGHBOR:/d" /etc/sonic/bgp_admin.yml
        if [ "$COMMAND" == "startup" ]; then
            echo "  $NEIGHBOR: on" >> /etc/sonic/bgp_admin.yml
        else
            echo "  $NEIGHBOR: off" >> /etc/sonic/bgp_admin.yml
        fi
    done

else
    # Examine bgp neighbor exists first
    vtysh -c "show ip bgp neighbor $NEIGHBOR_IP" | grep -q "BGP neighbor is"

    vtysh -c "configure terminal" -c "router bgp $ASN" -c "$CMD_PREFIX neighbor $NEIGHBOR_IP shutdown"

    # Save admin state in config file
    sed -i "/^\s*$NEIGHBOR_IP:/d" /etc/sonic/bgp_admin.yml
    if [ "$COMMAND" == "startup" ]; then
        echo "  $NEIGHBOR_IP: on" >> /etc/sonic/bgp_admin.yml
    else
        echo "  $NEIGHBOR_IP: off" >> /etc/sonic/bgp_admin.yml
    fi
fi
