#!/bin/bash

# Generate the following files from templates:
# 1. Monit configuration file of radv container
# 2. Monit configuration file of dhcp_relay container

CFGGEN_PARAMS=" \
    -d \
    -t /usr/share/sonic/templates/monit_radv.j2,/etc/monit/conf.d/monit_radv \
    -t /usr/share/sonic/templates/monit_dhcp_relay.j2,/etc/monit/conf.d/monit_dhcp_relay \
"
sonic-cfggen $CFGGEN_PARAMS
