FROM docker-base

RUN apt-get update

COPY deps /deps

RUN apt-get -y install libpcap-dev libxml2-dev python-dev swig libsensors4-dev

SED_DPKG

COPY ["start.sh", "/usr/bin/"]

## Clean up
RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
RUN rm -rf /deps

ENTRYPOINT ["/bin/bash"]
CMD ["/usr/bin/start.sh"]
