# sonic aboot installer

SONIC_GENERIC_ABOOT_IMAGE = sonic-aboot.bin
$(SONIC_GENERIC_ABOOT_IMAGE)_MACHINE = aboot
$(SONIC_GENERIC_ABOOT_IMAGE)_IMAGE_TYPE = aboot
$(SONIC_GENERIC_ABOOT_IMAGE)_DEPENDS =
$(SONIC_GENERIC_ABOOT_IMAGE)_DOCKERS =
SONIC_INSTALLERS += $(SONIC_GENERIC_ABOOT_IMAGE)

