# -*- Kbuild -*-
#
# Linux KNET Callback module.
#
# $Copyright: Copyright 2018-2021 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# A copy of the GNU General Public License version 2 (GPLv2) can
# be found in the LICENSES folder.$
#
ifeq ($(BUILD_PSAMPLE),1)
PSAMPLE_CFLAGS=-DPSAMPLE_SUPPORT
PSAMPLE_CB_OBJS=psample-cb.o
endif

obj-m := linux_ngknetcb.o

ccflags-y := $(KNETCB_CPPFLAGS) $(LKM_CFLAGS) \
	     $(SDK_PMD_KFLAGS) \
	     -I$(SDK)/shr/include \
	     -I$(SDK)/bcmdrd/include \
	     -I$(SDK)/bcmltd/include \
	     -I$(SDK)/bcmlrd/include \
	     -I$(SDK)/linux/include \
	     -I$(SDK)/linux/knet/include \
	     -I$(SDK)/linux/knetcb \
	     -I$(SDK)/linux/knet \
	     $(PSAMPLE_CFLAGS)

linux_ngknetcb-y := $(SDK_PMD_KOBJS) ngknetcb_main.o \
                    $(PSAMPLE_CB_OBJS)
