#!/bin/bash

if [[ -d /sys/devices/platform/SMF.512/hwmon/ ]]; then
    cd /sys/devices/platform/SMF.512/hwmon/*
    echo 0xcc > mb_poweron_reason
fi
/usr/local/bin/s6100_i2c_enumeration.sh deinit & > /dev/null
