#!/usr/bin/python
import sys
import os
import subprocess
import struct

PORT_RES = '/dev/port'


def log_software_reboot():
    # Run plugin script which will track the cli triggered reboot, fastboot, warmboot
    res = subprocess.check_output(['/usr/share/sonic/device/x86_64-dell_s6100_c2538-r0/fast-reboot_plugin'])
    return

def ssd_hdparm_upgrade():
    if os.path.exists('/tmp/SSD/SYS_S.bin'):
        res = subprocess.check_output(['/usr/share/sonic/device/x86_64-dell_s6100_c2538-r0/ssd-fw-upgrade', 'hdparm-upgrade'])
    return

def portio_reg_write(resource, offset, val):
    fd = os.open(resource, os.O_RDWR)
    if(fd < 0):
        print 'file open failed %s" % resource'
        return
    if(os.lseek(fd, offset, os.SEEK_SET) != offset):
        print 'lseek failed on %s' % resource
        return
    ret = os.write(fd, struct.pack('B', val))
    if(ret != 1):
        print 'write failed %d' % ret
        return
    os.close(fd)

if __name__ == "__main__":
    log_software_reboot()
    ssd_hdparm_upgrade()
    portio_reg_write(PORT_RES, 0xcf9, 0xe)

