#!/bin/sh

mr_reboot() {

    sudo rmmod x86-64-netberg-aurora-715
    sudo i2cset -y 0 0x30 0xa1 0  

}

if [ $# -eq 0 ] || [ $@ = "-p" ] || [ $@ = "--reboot" ] || [ $@ = "--poweroff" ] || [ $@ = "-f" ] || [ $@ = "--force" ];  then
    sync;sync
    mr_reboot
elif [ $@ = "--halt" ]; then
    sudo halt
else
    echo "unsupported option"
fi

