FROM docker-config-engine

# Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Update apt's package index files
RUN apt-get update

# Install required packages
RUN apt-get install -y python-pip sensord fancontrol

{% if docker_platform_monitor_debs.strip() -%}
# Copy all locally-built Debian package dependencies
COPY{{' '}}
{%- for deb in docker_platform_monitor_debs.split(' ') -%}
debs/{{ deb }}{{' '}}
{%- endfor -%}
/debs/

# Install all locally-built Debian package dependencies
# and implicitly install their dependencies
RUN dpkg_apt() { [ -f $1 ] && { dpkg -i $1 || apt-get -y install -f; } || return 1; }; dpkg_apt /debs/*.deb
{% endif %}

{% if docker_platform_monitor_whls.strip() -%}
# Copy all locally-built Python wheel dependencies
COPY{{' '}}
{%- for whl in docker_platform_monitor_whls.split(' ') -%}
python-wheels/{{ whl }}{{' '}}
{%- endfor -%}
/python-wheels/

# Install all locally-built Python wheel dependencies
RUN pip install /python-wheels/*.whl
{% endif %}

# Clean up
RUN apt-get remove -y python-pip
RUN apt-get clean -y
RUN apt-get autoclean -y
RUN apt-get autoremove -y
RUN rm -rf /debs /python-wheels ~/.cache

COPY ["start.sh", "lm-sensors.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]

ENTRYPOINT ["/usr/bin/supervisord"]
