# sonic kvm image

SONIC_KVM_IMAGE = sonic-xsight.img.gz
$(SONIC_KVM_IMAGE)_MACHINE = xsight
$(SONIC_KVM_IMAGE)_IMAGE_TYPE = kvm
$(SONIC_KVM_IMAGE)_INSTALLS += $($(SONIC_ONE_IMAGE)_INSTALLS)
$(SONIC_KVM_IMAGE)_LAZY_INSTALLS += $($(SONIC_ONE_IMAGE)_LAZY_INSTALLS)
ifeq ($(INSTALL_DEBUG_TOOLS),y)
$(SONIC_KVM_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_DBG_IMAGES)
$(SONIC_KVM_IMAGE)_DOCKERS += $(filter-out $(patsubst %-$(DBG_IMAGE_MARK).gz,%.gz, $(SONIC_INSTALL_DOCKER_DBG_IMAGES)), $(SONIC_INSTALL_DOCKER_IMAGES))
else
$(SONIC_KVM_IMAGE)_DOCKERS = $(SONIC_INSTALL_DOCKER_IMAGES)
endif
$(SONIC_KVM_IMAGE)_FILES = $(ONIE_RECOVERY_IMAGE)
SONIC_INSTALLERS += $(SONIC_KVM_IMAGE)
