# Accton Platform modules
ACCTON_ES9618XX_PLATFORM_MODULE_VERSION = 1.1

export ACCTON_ES9618XX_PLATFORM_MODULE_VERSION

ACCTON_ES9618XX_PLATFORM_MODULE = sonic-platform-accton-es9618xx_$(ACCTON_ES9618XX_PLATFORM_MODULE_VERSION)_amd64.deb
$(ACCTON_ES9618XX_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-accton
$(ACCTON_ES9618XX_PLATFORM_MODULE)_PLATFORM = x86_64-accton_es9618xx-r0
$(ACCTON_ES9618XX_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(ACCTON_ES9618XX_PLATFORM_MODULE) 


