obj-m:=i2c-ocores.o accton_as9817_32_fpga.o accton_as9817_32_fan.o \
	accton_as9817_32_psu.o accton_as9817_32_thermal.o accton_as9817_32_sys.o \
	accton_as9817_32_leds.o accton_as9817_32_mux.o accton_ipmi_intf.o
