#!/bin/bash
docker exec -i pmon sensors "$@"

#To probe sensors not part of lm-sensors
if [ -r /usr/local/bin/cameo_esc600_sensors.py ]; then
        python /usr/local/bin/cameo_esc600_sensors.py fan_status
        python /usr/local/bin/cameo_esc600_sensors.py sensor_status
fi
