# obj-m:=accton_as7712_32x_fan.o accton_as7712_32x_sfp.o leds-accton_as7712_32x.o \
#        goreme_system_cpld.o ym2651y.o optoe.o

obj-m:=snj60d0-320f_i2c_mux_cpld.o snj60d0-320f_fpga.o snj60d0-320f_onie_eeprom.o yesm1300am.o


# obj-m:=accton_as7712_32x_fan.o accton_as7712_32x_sfp.o leds-accton_as7712_32x.o \
#        accton_as7712_32x_psu.o accton_i2c_cpld.o ym2651y.o optoe.o
