#!/usr/bin/env python3

"""
    i2chealthd
    I2C health monitor daemon for SONiC
"""


from sonic_py_common import daemon_base, device_info
import threading
import signal
import sys

SYSLOG_IDENTIFIER = 'i2c-healthd'

I2C_HEALTH_UPDATE_PERIOD_SECS = 60

class I2CHealthDaemon(daemon_base.DaemonBase):


    def __init__(self):
        """
        A daemon that run as a service to perform i2c health checker with an interval.
        """

        daemon_base.DaemonBase.__init__(self, SYSLOG_IDENTIFIER)
        self.stop_event = threading.Event()
        self.log_level = 'notice'
        self.interval = I2C_HEALTH_UPDATE_PERIOD_SECS




    def deinit(self):
        """
        Destructor. Remove all entries in DB
        :return:
        """


        pass

    def run(self):
        '''
        Check i2c health in an infinite loop.
        '''
        self.log_notice("Starting up...")

        try:
            # Polling i2c devices task
            while True:
                # Do the I2C BUS check here
                if self.stop_event.wait(self.interval):
                    break

                self.log_notice("Wait Event timeout, do I2C check...")

        except:
            pass


        self.deinit()


    # Signal handler
    def signal_handler(self, sig, frame):
        """
        Signal handler
        :param sig: Signal number
        :param frame: not used
        :return:
        """
        if sig == signal.SIGHUP:
            self.log_notice("Caught SIGHUP - ignoring...")
        elif sig == signal.SIGINT:
            self.log_notice("Caught SIGINT - exiting...")
            self.stop_event.set()
        elif sig == signal.SIGTERM:
            self.log_notice("Caught SIGTERM - exiting...")
            self.stop_event.set()
        else:
            self.log_warning("Caught unhandled signal '" + sig + "'")

#
# Main =========================================================================
#
def main():
    i2c_healthd = I2CHealthDaemon()
    i2c_healthd.run()


if __name__ == '__main__':
    main()