# Ingrasys S9100 Platform modules

INGRASYS_S9100_PLATFORM_MODULE_VERSION = 1.0.0

export INGRASYS_S9100_PLATFORM_MODULE_VERSION

INGRASYS_S9100_PLATFORM_MODULE = sonic-platform-ingrasys-s9100_$(INGRASYS_S9100_PLATFORM_MODULE_VERSION)_amd64.deb
$(INGRASYS_S9100_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-ingrasys-s9100
$(INGRASYS_S9100_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
SONIC_DPKG_DEBS += $(INGRASYS_S9100_PLATFORM_MODULE)
