# Broadcom XLR/GTS Platform modules

BRCM_XLR_GTS_PLATFORM_MODULE_VERSION = 1.0

export BRCM_XLR_GTS_PLATFORM_MODULE_VERSION

BRCM_XLR_GTS_PLATFORM_MODULE = sonic-platform-brcm-xlr-gts_$(BRCM_XLR_GTS_PLATFORM_MODULE_VERSION)_amd64.deb
$(BRCM_XLR_GTS_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-brcm-xlr-gts
$(BRCM_XLR_GTS_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BRCM_XLR_GTS_PLATFORM_MODULE)_PLATFORM = x86_64-bcm_xlr-r0
SONIC_MAKE_DEBS += $(BRCM_XLR_GTS_PLATFORM_MODULE)

export BRCM_XLR_GTS_PLATFORM_MODULE 

