# Broadcom SAI modules

BRCM_MODULES_DEB_PKG_VERSION = 6.5.23+20230213-1

BRCM_OPENNSL_KERNEL = saibcm-modules_$(BRCM_MODULES_DEB_PKG_VERSION)_amd64.deb
$(BRCM_OPENNSL_KERNEL)_PATH = ec_sai
SONIC_COPY_DEBS += $(BRCM_OPENNSL_KERNEL)
