LIBSAIBCM_XGS_VERSION = 10.1.6.0
LIBSAIBCM_DNX_VERSION = 7.1.111.1
LIBSAIBCM_XGS_BRANCH_NAME = SAI_10.1.0_GA
LIBSAIBCM_DNX_BRANCH_NAME = REL_7.0_SAI_1.11
LIBSAIBCM_XGS_URL_PREFIX = "https://packages.trafficmanager.net/public/sai/sai-broadcom/$(LIBSAIBCM_XGS_BRANCH_NAME)/$(LIBSAIBCM_XGS_VERSION)/xgs"
LIBSAIBCM_DNX_URL_PREFIX = "https://packages.trafficmanager.net/public/sai/bcmsai/$(LIBSAIBCM_DNX_BRANCH_NAME)/$(LIBSAIBCM_DNX_VERSION)"

TOPDIR := $(shell pwd)
LOCAL_SAI_PATH = $(TOPDIR)/files/local_files/debs

BRCM_XGS_SAI = libsaibcm_$(LIBSAIBCM_XGS_VERSION)_amd64.deb
$(BRCM_XGS_SAI)_PATH = $(LOCAL_SAI_PATH)

BRCM_XGS_SAI_DEV = libsaibcm-dev_$(LIBSAIBCM_XGS_VERSION)_amd64.deb
$(eval $(call add_derived_package,$(BRCM_XGS_SAI),$(BRCM_XGS_SAI_DEV)))
$(BRCM_XGS_SAI_DEV)_PATH = $(LOCAL_SAI_PATH)

# SAI module for DNX Asic family
BRCM_DNX_SAI = libsaibcm_dnx_$(LIBSAIBCM_DNX_VERSION)_amd64.deb
$(BRCM_DNX_SAI)_PATH = $(LOCAL_SAI_PATH)

SONIC_COPY_DEBS += $(BRCM_XGS_SAI)
SONIC_COPY_DEBS += $(BRCM_DNX_SAI)
$(BRCM_XGS_SAI_DEV)_DEPENDS += $(BRCM_XGS_SAI)

$(BRCM_XGS_SAI)_SKIP_VERSION=y
$(BRCM_XGS_SAI_DEV)_SKIP_VERSION=y
$(BRCM_DNX_SAI)_SKIP_VERSION=y

$(eval $(call add_conflict_package,$(BRCM_XGS_SAI_DEV),$(LIBSAIVS_DEV)))
