# Delta Platform modules

DELTA_ETC032IF_PLATFORM_MODULE_VERSION = 1.1

export DELTA_ETC032IF_PLATFORM_MODULE_VERSION

DELTA_PLATFORM_MODULE = platform-modules-et-c032if_$(DELTA_ETC032IF_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(DELTA_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-delta
$(DELTA_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(DELTA_PLATFORM_MODULE)_PLATFORM = x86_64-delta_et-c032if-r0

SONIC_DPKG_DEBS += $(DELTA_PLATFORM_MODULE)
