# Netberg Platform modules

NETBERG_AURORA_715_PLATFORM_MODULE_VERSION = 1.0.0

export NETBERG_AURORA_715_PLATFORM_MODULE_VERSION

NETBERG_AURORA_715_PLATFORM_MODULE = sonic-platform-netberg-aurora-715_$(NETBERG_AURORA_715_PLATFORM_MODULE_VERSION)_amd64.deb
$(NETBERG_AURORA_715_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-netberg
$(NETBERG_AURORA_715_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(NETBERG_AURORA_715_PLATFORM_MODULE)_PLATFORM = x86_64-netberg_aurora_715-r0
SONIC_DPKG_DEBS += $(NETBERG_AURORA_715_PLATFORM_MODULE)

SONIC_STRETCH_DEBS +=$(NETBERG_AURORA_715_PLATFORM_MODULE)
