# Delta Platform modules

DELTA_ETC032IF_PLATFORM_MODULE_VERSION = 1.1
DELTA_EVSA32Q56_PLATFORM_MODULE_VERSION = 1.1

export DELTA_ETC032IF_PLATFORM_MODULE_VERSION
export DELTA_EVSA32Q56_PLATFORM_MODULE_VERSION

DELTA_ETC032IF_PLATFORM_MODULE = platform-modules-et-c032if_$(DELTA_ETC032IF_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(DELTA_ETC032IF_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-delta
$(DELTA_ETC032IF_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(DELTA_ETC032IF_PLATFORM_MODULE)_PLATFORM = x86_64-delta_et-c032if-r0
SONIC_DPKG_DEBS += $(DELTA_ETC032IF_PLATFORM_MODULE)

DELTA_EVSA32Q56_PLATFORM_MODULE = platform-modules-evs-a-32q56_$(DELTA_EVSA32Q56_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(DELTA_EVSA32Q56_PLATFORM_MODULE)_PLATFORM = x86_64-delta_evs-a-32q56-r0
$(eval $(call add_extra_package,$(DELTA_ETC032IF_PLATFORM_MODULE),$(DELTA_EVSA32Q56_PLATFORM_MODULE)))

SONIC_STRETCH_DEBS += $(DELTA_ETC032IF_PLATFORM_MODULE)
