obj-m:=i2c-ocores.o accton_as9737_32db_fpga.o accton_as9737_32db_mux.o accton_as9737_32db_cpld.o \
	accton_as9737_32db_psu.o accton_as9737_32db_fan.o accton_as9737_32db_thermal.o \
	accton_as9737_32db_leds.o accton_as9737_32db_sys.o
