#!/bin/bash

IMAGENAME=$1

. /usr/local/share/buildinfo/scripts/buildinfo_base.sh

# Collect the version files
collect_version_files $POST_VERSION_PATH

#Save the cache file for exporting it to host.
tar -C ${PKG_CACHE_PATH} --exclude=cache.tgz -zcvf /cache.tgz .

# Disable the build hooks
symlink_build_hooks -d
set_reproducible_mirrors -d

# Remove the version deb preference
rm -f $VERSION_DEB_PREFERENCE
