/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * Tool: INTERNAL/drd/instpkgs.pl
 *
 * $Copyright: Copyright 2018-2021 Broadcom. All rights reserved.
 * The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * A copy of the GNU General Public License version 2 (GPLv2) can
 * be found in the LICENSES folder.$
 */

/*
 * This file contains the complete list of supported devices.
 * No other device lists should be used anywhere in the SDK.
 */

#ifndef BCMDRD_DEVIDS_H
#define BCMDRD_DEVIDS_H

#include <bcmdrd_config.h>

/*
 * All Supported Devices and Revisions
 */

#define BROADCOM_VENDOR_ID                0x14e4
#define BROADCOM_PHYID_MSB                0x0143

/* BCM56780 */
#define BCM56780_VENDOR_ID                0x14e4
#define BCM56780_DEVICE_ID                0xb780
#define BCM56780_REV_A0                     0x01

/* BCM56782 */
#define BCM56782_VENDOR_ID                0x14e4
#define BCM56782_DEVICE_ID                0xb782
#define BCM56782_REV_A0                     0x01

/* BCM56784 */
#define BCM56784_VENDOR_ID                0x14e4
#define BCM56784_DEVICE_ID                0xb784
#define BCM56784_REV_A0                     0x01

/* BCM56785 */
#define BCM56785_VENDOR_ID                0x14e4
#define BCM56785_DEVICE_ID                0xb785
#define BCM56785_REV_A0                     0x01

/* BCM56786 */
#define BCM56786_VENDOR_ID                0x14e4
#define BCM56786_DEVICE_ID                0xb786
#define BCM56786_REV_A0                     0x01

/* BCM56787 */
#define BCM56787_VENDOR_ID                0x14e4
#define BCM56787_DEVICE_ID                0xb787
#define BCM56787_REV_A0                     0x01

/* BCM56788 */
#define BCM56788_VENDOR_ID                0x14e4
#define BCM56788_DEVICE_ID                0xb788
#define BCM56788_REV_A0                     0x01

/* BCM56789 */
#define BCM56789_VENDOR_ID                0x14e4
#define BCM56789_DEVICE_ID                0xb789
#define BCM56789_REV_A0                     0x01

/* BCM56880 */
#define BCM56880_VENDOR_ID                0x14e4
#define BCM56880_DEVICE_ID                0xb880
#define BCM56880_REV_A0                     0x01
#define BCM56880_REV_B0                     0x11

/* BCM56881 */
#define BCM56881_VENDOR_ID                0x14e4
#define BCM56881_DEVICE_ID                0xb881
#define BCM56881_REV_A0                     0x01
#define BCM56881_REV_B0                     0x11

/* BCM56883 */
#define BCM56883_VENDOR_ID                0x14e4
#define BCM56883_DEVICE_ID                0xb883
#define BCM56883_REV_A0                     0x01
#define BCM56883_REV_B0                     0x11

/* BCM56990 */
#define BCM56990_VENDOR_ID                0x14e4
#define BCM56990_DEVICE_ID                0xb990
#define BCM56990_REV_A0                     0x01
#define BCM56990_REV_B0                     0x11

/* BCM56991 */
#define BCM56991_VENDOR_ID                0x14e4
#define BCM56991_DEVICE_ID                0xb991
#define BCM56991_REV_B0                     0x11

/* BCM56992 */
#define BCM56992_VENDOR_ID                0x14e4
#define BCM56992_DEVICE_ID                0xb992
#define BCM56992_REV_B0                     0x11

/* BCM56995 */
#define BCM56995_VENDOR_ID                0x14e4
#define BCM56995_DEVICE_ID                0xb995
#define BCM56995_REV_A0                     0x01

/* BCM56996 */
#define BCM56996_VENDOR_ID                0x14e4
#define BCM56996_DEVICE_ID                0xb996
#define BCM56996_REV_A0                     0x01
#define BCM56996_REV_B0                     0x11

/* BCM56997 */
#define BCM56997_VENDOR_ID                0x14e4
#define BCM56997_DEVICE_ID                0xb997
#define BCM56997_REV_A0                     0x01
#define BCM56997_REV_B0                     0x11

/* BCM56998 */
#define BCM56998_VENDOR_ID                0x14e4
#define BCM56998_DEVICE_ID                0xb998
#define BCM56998_REV_A0                     0x01

/*
 * End of Supported Devices and Revisions
 */

#endif /* BCMDRD_DEVIDS_H */

#ifdef BCMDRD_DEVLIST_ENTRY
/*
 * BCMDRD_DEVLIST_ENTRY macros.
 *
 * Before including this file, define BCMDRD_DEVLIST_ENTRY
 * as a macro to operate on the following parameters:
 *
 *     #define BCMDRD_DEVLIST_ENTRY(_nm,_vn,_dv,_rv,_md,_pi,_bd,_bc,_fn,_cn,_pf,_pd,_r0,_r1)
 *
 *     _nm: Chip Name
 *     _vn: Chip Vendor ID
 *     _dv: Chip Device ID
 *     _rv: Chip Revision
 *     _md: Chip Model
 *     _pi: Probe Information
 *     _bd: SW Base Driver
 *     _bc: SW Base Configuration
 *     _fn: SW Full Name
 *     _cn: Code Name
 *     _pf: Product Family
 *     _pd: Product Description
 *     _r0: Reserved
 *     _r1: Reserved
 *
 * Note that this macro will be undefined at the end of this file.
 */

#if BCMDRD_CONFIG_INCLUDE_BCM56780_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM56780, BCM56780_VENDOR_ID, BCM56780_DEVICE_ID, BCM56780_REV_A0, \
                     0, 0, \
                     bcm56780_a0, bcm56780_a0, bcm56780_a0, \
                     "Trident4-X9", "BCM56780", \
                     "8 Tb/s 160x50G-PAM4 Programmable Switch", 0, 0)
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56782_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56782, BCM56782_VENDOR_ID, BCM56782_DEVICE_ID, BCM56782_REV_A0, \
                     0, 0, \
                     bcm56780_a0, bcm56782_a0, bcm56782_a0, \
                     "Trident4-X9", "BCM56780", \
                     "8 Tb/s 160x50G-PAM4 Programmable Switch w/MACsec", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56784_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56784, BCM56784_VENDOR_ID, BCM56784_DEVICE_ID, BCM56784_REV_A0, \
                     0, 0, \
                     bcm56780_a0, bcm56784_a0, bcm56784_a0, \
                     "Trident4-X9", "BCM56780", \
                     "5.6 Tb/s 96x50G-PAM4/32x35G-NRZ Programmable Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56785_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56785, BCM56785_VENDOR_ID, BCM56785_DEVICE_ID, BCM56785_REV_A0, \
                     0, 0, \
                     bcm56780_a0, bcm56785_a0, bcm56785_a0, \
                     "Trident4-X9", "BCM56780", \
                     "5.6 Tb/s 96x50G-PAM4/32x35G-NRZ Programmable Switch w/SmartToR", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56786_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56786, BCM56786_VENDOR_ID, BCM56786_DEVICE_ID, BCM56786_REV_A0, \
                     0, 0, \
                     bcm56780_a0, bcm56786_a0, bcm56786_a0, \
                     "Trident4-X9", "BCM56780", \
                     "5.6 Tb/s 96x50G-PAM4/32x35G-NRZ Programmable Switch w/MACsec", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56787_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56787, BCM56787_VENDOR_ID, BCM56787_DEVICE_ID, BCM56787_REV_A0, \
                     0, 0, \
                     bcm56780_a0, bcm56787_a0, bcm56787_a0, \
                     "Trident4-X9", "BCM56780", \
                     "5.6 Tb/s 96x50G-PAM4/32x35G-NRZ Programmable Switch w/MACsec w/SmartToR", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56788_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56788, BCM56788_VENDOR_ID, BCM56788_DEVICE_ID, BCM56788_REV_A0, \
                     0, 0, \
                     bcm56780_a0, bcm56788_a0, bcm56788_a0, \
                     "Trident4-X9", "BCM56780", \
                     "8 Tb/s 160x50G-PAM4 Programmable Switch w/MACsec w/SmartToR", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56789_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56789, BCM56789_VENDOR_ID, BCM56789_DEVICE_ID, BCM56789_REV_A0, \
                     0, 0, \
                     bcm56780_a0, bcm56789_a0, bcm56789_a0, \
                     "Trident4-X9", "BCM56780", \
                     "8 Tb/s 160x50G-PAM4 Programmable Switch w/SmartToR", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56880_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM56880, BCM56880_VENDOR_ID, BCM56880_DEVICE_ID, BCM56880_REV_A0, \
                     0, 0, \
                     bcm56880_a0, bcm56880_a0, bcm56880_a0, \
                     "Trident4", "BCM56880", \
                     "12.8 Tb/s Switch Fabric 128x100G/64x200G/32x400G Multilayer Switch", 0, 0)
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56880_B0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56880, BCM56880_VENDOR_ID, BCM56880_DEVICE_ID, BCM56880_REV_B0, \
                     0, 0, \
                     bcm56880_a0, bcm56880_a0, bcm56880_b0, \
                     "Trident4", "BCM56880", \
                     "12.8 Tb/s Switch Fabric 128x100G/64x200G/32x400G Multilayer Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56881_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56881, BCM56881_VENDOR_ID, BCM56881_DEVICE_ID, BCM56881_REV_A0, \
                     0, 0, \
                     bcm56880_a0, bcm56881_a0, bcm56881_a0, \
                     "Trident4", "BCM56880", \
                     "12.8 Tb/s Switch Fabric 128x100G/64x200G/32x400G Multilayer Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56881_B0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56881, BCM56881_VENDOR_ID, BCM56881_DEVICE_ID, BCM56881_REV_B0, \
                     0, 0, \
                     bcm56880_a0, bcm56881_a0, bcm56881_b0, \
                     "Trident4", "BCM56880", \
                     "12.8 Tb/s Switch Fabric 128x100G/64x200G/32x400G Multilayer Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56883_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56883, BCM56883_VENDOR_ID, BCM56883_DEVICE_ID, BCM56883_REV_A0, \
                     0, 0, \
                     bcm56880_a0, bcm56883_a0, bcm56883_a0, \
                     "Trident4", "BCM56880", \
                     "8.0 Tb/s Switch Fabric 80x100G/40x200G/20x400G Multilayer Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56883_B0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56883, BCM56883_VENDOR_ID, BCM56883_DEVICE_ID, BCM56883_REV_B0, \
                     0, 0, \
                     bcm56880_a0, bcm56883_a0, bcm56883_b0, \
                     "Trident4", "BCM56880", \
                     "8.0 Tb/s Switch Fabric 80x100G/40x200G/20x400G Multilayer Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56990_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM56990, BCM56990_VENDOR_ID, BCM56990_DEVICE_ID, BCM56990_REV_A0, \
                     0, 0, \
                     bcm56990_a0, bcm56990_a0, bcm56990_a0, \
                     "Tomahawk4", "BCM56990", \
                     "25.6 Tbps Multilayer Switch", 0, 0)
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56990_B0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM56990, BCM56990_VENDOR_ID, BCM56990_DEVICE_ID, BCM56990_REV_B0, \
                     0, 0, \
                     bcm56990_b0, bcm56990_b0, bcm56990_b0, \
                     "Tomahawk4", "BCM56990", \
                     "25.6 Tbps Multilayer Switch", 0, 0)
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56991_B0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56991, BCM56991_VENDOR_ID, BCM56991_DEVICE_ID, BCM56991_REV_B0, \
                     0, 0, \
                     bcm56990_b0, bcm56991_b0, bcm56991_b0, \
                     "Tomahawk4", "BCM56990", \
                     "25.6 Tbps Multilayer Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56992_B0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56992, BCM56992_VENDOR_ID, BCM56992_DEVICE_ID, BCM56992_REV_B0, \
                     0, 0, \
                     bcm56990_b0, bcm56992_b0, bcm56992_b0, \
                     "Tomahawk4", "BCM56990", \
                     "25.6 Tbps Multilayer Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56995_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM56995, BCM56995_VENDOR_ID, BCM56995_DEVICE_ID, BCM56995_REV_A0, \
                     0, 0, \
                     bcm56995_a0, bcm56995_a0, bcm56995_a0, \
                     "Tomahawk4D", "BCM56995", \
                     "25.6 Tbps Multilayer Switch", 0, 0)
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56996_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM56996, BCM56996_VENDOR_ID, BCM56996_DEVICE_ID, BCM56996_REV_A0, \
                     0, 0, \
                     bcm56996_a0, bcm56996_a0, bcm56996_a0, \
                     "Tomahawk4G", "BCM56996", \
                     "25.6 Tbps Multilayer Switch", 0, 0)
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56996_B0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM56996, BCM56996_VENDOR_ID, BCM56996_DEVICE_ID, BCM56996_REV_B0, \
                     0, 0, \
                     bcm56996_b0, bcm56996_b0, bcm56996_b0, \
                     "Tomahawk4G", "BCM56996", \
                     "25.6 Tbps Multilayer Switch", 0, 0)
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56997_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56997, BCM56997_VENDOR_ID, BCM56997_DEVICE_ID, BCM56997_REV_A0, \
                     0, 0, \
                     bcm56996_a0, bcm56997_a0, bcm56997_a0, \
                     "Tomahawk4G", "BCM56996", \
                     "12.8 Tbps Multilayer Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56997_B0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
BCMDRD_DEVLIST_ENTRY(BCM56997, BCM56997_VENDOR_ID, BCM56997_DEVICE_ID, BCM56997_REV_B0, \
                     0, 0, \
                     bcm56996_b0, bcm56997_b0, bcm56997_b0, \
                     "Tomahawk4G", "BCM56996", \
                     "12.8 Tbps Multilayer Switch", 0, 0)
#endif
#endif

#if BCMDRD_CONFIG_INCLUDE_BCM56998_A0 == 1 || defined(BCMDRD_DEVLIST_OVERRIDE)
BCMDRD_DEVLIST_ENTRY(BCM56998, BCM56998_VENDOR_ID, BCM56998_DEVICE_ID, BCM56998_REV_A0, \
                     0, 0, \
                     bcm56998_a0, bcm56998_a0, bcm56998_a0, \
                     "Tomahawk4GT", "BCM56998", \
                     "12.8 Tbps Multilayer Switch", 0, 0)
#endif

/* End BCMDRD_DEVLIST_ENTRY Macros */

#ifdef BCMDRD_DEVLIST_INCLUDE_ALL
#undef BCMDRD_DEVLIST_INCLUDE_ALL
#endif
#ifdef BCMDRD_DEVLIST_OVERRIDE
#undef BCMDRD_DEVLIST_OVERRIDE
#endif
#undef BCMDRD_DEVLIST_ENTRY
#endif /* BCMDRD_DEVLIST_ENTRY */
