d6556/utils/inventec_d6556_util.py usr/local/bin
common/utils/transceiver_monitor.py usr/share/sonic/device/x86_64-inventec_d6556-r0/plugins
common/utils/led_proc.py usr/share/sonic/device/x86_64-inventec_d6556-r0/plugins
common/utils/asic_monitor.py usr/share/sonic/device/x86_64-inventec_d6556-r0/plugins
common/utils/platform_status.py usr/share/sonic/device/x86_64-inventec_d6556-r0/plugins
systemd/platform-modules-d6556.service lib/systemd/system
