d6254qs/utils/inventec_d6254_util.py usr/local/bin
common/utils/transceiver_monitor.py usr/share/sonic/device/x86_64-inventec_d6254qs-r0/plugins
common/utils/led_proc.py usr/share/sonic/device/x86_64-inventec_d6254qs-r0/plugins
common/utils/asic_monitor.py usr/share/sonic/device/x86_64-inventec_d6254qs-r0/plugins
common/utils/platform_status.py usr/share/sonic/device/x86_64-inventec_d6254qs-r0/plugins
systemd/platform-modules-d6254qs.service lib/systemd/system
