# Nokia Platform

NOKIA_7215_PLATFORM_VERSION = 1.0
export NOKIA_7215_PLATFORM_VERSION
SONIC_KERNEL_DEB_PKG = $(LINUX_KERNEL)
export SONIC_KERNEL_DEB_PKG

NOKIA_7215_PLATFORM = sonic-platform-nokia-7215_$(NOKIA_7215_PLATFORM_VERSION)_$(CONFIGURED_ARCH).deb
$(NOKIA_7215_PLATFORM)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-nokia
$(NOKIA_7215_PLATFORM)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(NOKIA_7215_PLATFORM)_PLATFORM = arm64-nokia_ixs7215_52xb-r0

MPATH       := $($(NOKIA_7215_PLATFORM)_SRC_PATH)
DEP_FILES   := $(SONIC_COMMON_FILES_LIST) platform/marvell-arm64/platform-nokia.mk
DEP_FILES   += $(SONIC_COMMON_BASE_FILES_LIST)
DEP_FILES   += $(shell git ls-files $(MPATH))

$(NOKIA_7215_PLATFORM)_CACHE_MODE  := GIT_CONTENT_SHA
$(NOKIA_7215_PLATFORM)_DEP_FLAGS   := $(SONIC_COMMON_FLAGS_LIST)
$(NOKIA_7215_PLATFORM)_DEP_FILES   := $(DEP_FILES)

SONIC_DPKG_DEBS += $(NOKIA_7215_PLATFORM)

