# docker image for orchagent

DOCKER_ORCHAGENT = docker-orchagent.gz
$(DOCKER_ORCHAGENT)_PATH = $(DOCKERS_PATH)/docker-orchagent
$(DOCKER_ORCHAGENT)_DEPENDS += $(SWSS)
$(DOCKER_ORCHAGENT)_LOAD_DOCKERS += $(DOCKER_BASE)
SONIC_DOCKER_IMAGES += $(DOCKER_ORCHAGENT)
