# docker image for sonic swss layer

DOCKER_SWSS_LAYER_BUSTER = docker-swss-layer-buster.gz
$(DOCKER_SWSS_LAYER_BUSTER)_PATH = $(DOCKERS_PATH)/docker-swss-layer-buster

$(DOCKER_SWSS_LAYER_BUSTER)_DEPENDS += $(SWSS)
$(DOCKER_SWSS_LAYER_BUSTER)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BUSTER)

$(DOCKER_SWSS_LAYER_BUSTER)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_DEPENDS) \
                                             $(SWSS)
$(DOCKER_SWSS_LAYER_BUSTER)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BUSTER)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_SWSS_LAYER_BUSTER)
SONIC_BUSTER_DOCKERS += $(DOCKER_SWSS_LAYER_BUSTER)
