# flashrom package
#

FLASHROM_VERSION_FULL = 0.9.7

export FLASHROM_VERSION_FULL

FLASHROM = flashrom_$(FLASHROM_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(FLASHROM)_SRC_PATH = $(SRC_PATH)/flashrom

SONIC_MAKE_DEBS += $(FLASHROM)
