# libyang1

LIBYANG1_VERSION_BASE = 1.0
LIBYANG1_VERSION = $(LIBYANG1_VERSION_BASE).184
LIBYANG1_SUBVERSION = 2
LIBYANG1_FULLVERSION = $(LIBYANG1_VERSION)-$(LIBYANG1_SUBVERSION)

export LIBYANG1_VERSION_BASE
export LIBYANG1_VERSION
export LIBYANG1_SUBVERSION
export LIBYANG1_FULLVERSION

LIBYANG1 = libyang1_$(LIBYANG1_FULLVERSION)_$(CONFIGURED_ARCH).deb
$(LIBYANG1)_SRC_PATH = $(SRC_PATH)/libyang1
SONIC_MAKE_DEBS += $(LIBYANG1)

LIBYANG1_DEV = libyang-dev_$(LIBYANG1_FULLVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBYANG1),$(LIBYANG1_DEV)))

LIBYANG1_DBG = libyang1-dbgsym_$(LIBYANG1_FULLVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBYANG1),$(LIBYANG1_DBG)))

LIBYANG1_CPP = libyang-cpp1_$(LIBYANG1_FULLVERSION)_$(CONFIGURED_ARCH).deb
$(LIBYANG1_CPP)_DEPENDS += $(LIBYANG1)
$(eval $(call add_derived_package,$(LIBYANG1),$(LIBYANG1_CPP)))

LIBYANG1_CPP_DEV = libyang-cpp-dev_$(LIBYANG1_FULLVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBYANG1),$(LIBYANG1_CPP_DEV)))

LIBYANG1_CPP_DBG = libyang-cpp1-dbgsym_$(LIBYANG1_FULLVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBYANG1),$(LIBYANG1_CPP_DBG)))

YANG_TOOLS = yang-tools_$(LIBYANG1_FULLVERSION)_all.deb
$(YANG_TOOLS)_DEPENDS += $(LIBYANG1)
$(eval $(call add_derived_package,$(LIBYANG1),$(YANG_TOOLS)))

LIBYANG1_TOOLS = libyang-tools_$(LIBYANG1_FULLVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBYANG1),$(LIBYANG1_TOOLS)))

LIBYANG1_TOOLS_DBG = libyang-tools-dbgsym_$(LIBYANG1_FULLVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBYANG1),$(LIBYANG1_TOOLS_DBG)))

export LIBYANG1 LIBYANG1_DBG LIBYANG1_DEV LIBYANG1_CPP LIBYANG1_CPP_DEV LIBYANG1_CPP_DBG YANG_TOOLS LIBYANG1_TOOLS LIBYANG1_TOOLS_DBG
