# openssh package

OPENSSH_VERSION = 8.4p1
OPENSSH_VERSION_FULL = ${OPENSSH_VERSION}-2~bpo10+1

export OPENSSH_VERSION OPENSSH_VERSION_FULL

OPENSSH_SERVER = openssh-server_$(OPENSSH_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(OPENSSH_SERVER)_SRC_PATH = $(SRC_PATH)/openssh
SONIC_MAKE_DEBS += $(OPENSSH_SERVER)

OPENSSH_SERVER_DBG = openssh-server-dbgsym_$(OPENSSH_VERSION_FULL)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(OPENSSH_SERVER),$(OPENSSH_SERVER_DBG)))

export OPENSSH_SERVER OPENSSH_SERVER_DBG
