# genl-packet listener package
GENL_PACKET_VERSION = 1.0-1
GENL_PACKET_DIR = sonic-genl-packet

LIBGENL_PACKET_NAME = libgenl-packet
LIBGENL_PACKET = $(LIBGENL_PACKET_NAME)_$(GENL_PACKET_VERSION)_$(CONFIGURED_ARCH).deb
$(LIBGENL_PACKET)_SRC_PATH = $(SRC_PATH)/$(GENL_PACKET_DIR)/libgenl-packet
$(LIBGENL_PACKET)_VERSION = $(LIBGENL_PACKET_VERSION)
$(LIBGENL_PACKET)_NAME = $(LIBGENL_PACKET_NAME)
$(LIBGENL_PACKET)_DEPENDS += $(LIBNL3_DEV)  $(LIBNL_GENL3_DEV) 
$(LIBGENL_RDEPENDS += $(LIBNL3)  $(LIBNL_GENL3) 
SONIC_DPKG_DEBS += $(LIBGENL_PACKET)

LIBGENL_PACKET_DEV= $(LIBGENL_PACKET_NAME)-dev_$(GENL_PACKET_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(LIBGENL_PACKET),$(LIBGENL_PACKET_DEV)))

