# sonic-yang-mgmt python3 wheel

SONIC_YANG_MGMT_PY3 = sonic_yang_mgmt-1.0-py3-none-any.whl
$(SONIC_YANG_MGMT_PY3)_SRC_PATH = $(SRC_PATH)/sonic-yang-mgmt
$(SONIC_YANG_MGMT_PY3)_PYTHON_VERSION = 3
$(SONIC_YANG_MGMT_PY3)_DEBS_DEPENDS = $(LIBYANG) $(LIBYANG_CPP) $(LIBYANG_PY3)
$(SONIC_YANG_MGMT_PY3)_DEPENDS =  $(SONIC_YANG_MODELS_PY3)
$(SONIC_YANG_MGMT_PY3)_RDEPENDS = $(SONIC_YANG_MODELS_PY3) $(LIBYANG) \
                                 $(LIBYANG_CPP) $(LIBYANG_PY3)

SONIC_PYTHON_WHEELS += $(SONIC_YANG_MGMT_PY3)
