# sonic-bgpcfgd package

SONIC_CONTAINERCFGD = sonic_containercfgd-1.0-py3-none-any.whl
$(SONIC_CONTAINERCFGD)_SRC_PATH = $(SRC_PATH)/sonic-containercfgd
$(SONIC_CONTAINERCFGD)_DEPENDS += $(SONIC_PY_COMMON_PY3)
$(SONIC_CONTAINERCFGD)_DEBS_DEPENDS = $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)
$(SONIC_CONTAINERCFGD)_PYTHON_VERSION = 3
SONIC_PYTHON_WHEELS += $(SONIC_CONTAINERCFGD)
