# sonic-device-data Debian package

SONIC_DEVICE_DATA_VERSION = 1.0
SONIC_DEVICE_DATA_VERSION_FULL = $(SONIC_DEVICE_DATA_VERSION)-1

export SONIC_DEVICE_DATA_VERSION SONIC_DEVICE_DATA_VERSION_FULL

SONIC_DEVICE_DATA = sonic-device-data_$(SONIC_DEVICE_DATA_VERSION_FULL)_all.deb
$(SONIC_DEVICE_DATA)_SRC_PATH = $(SRC_PATH)/sonic-device-data
SONIC_MAKE_DEBS += $(SONIC_DEVICE_DATA)
