# swig

SWIG_VERSION_BASE = 3.0
SWIG_VERSION = $(SWIG_VERSION_BASE).12
SWIG_SUBVERSION = 2

export SWIG_VERSION_BASE
export SWIG_VERSION
export SWIG_SUBVERSION

SWIG_BASE = swig$(SWIG_VERSION_BASE)_$(SWIG_VERSION)-$(SWIG_SUBVERSION)_$(CONFIGURED_ARCH).deb
$(SWIG_BASE)_SRC_PATH = $(SRC_PATH)/swig
SONIC_MAKE_DEBS += $(SWIG_BASE)
SONIC_STRETCH_DEBS += $(SWIG_BASE)

SWIG = swig_$(SWIG_VERSION)-$(SWIG_SUBVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(SWIG_BASE),$(SWIG)))

SWIG_DBG = swig$(SWIG_VERSION_BASE)-dbgsym_$(SWIG_VERSION)-$(SWIG_SUBVERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(SWIG_BASE),$(SWIG_DBG)))

export SWIG_BASE SWIG SWIG_DBG
