# -*- Kbuild -*-
#
# Linux kernel BDE module.
#
# The NGBDE_CFLAGS variable is intended for configuring non-default
# builds of the NGBDE kernel module, for example, using a different
# default DMA pool size or turning off MSI interrupts.
#
# $Copyright: Copyright 2018-2022 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 
# version 2 as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# A copy of the GNU General Public License version 2 (GPLv2) can
# be found in the LICENSES folder.$
#

obj-m := linux_ngbde.o

ccflags-y := $(LKM_CFLAGS) $(NGBDE_CFLAGS) \
             -I$(SDK)/linux/include \
             -I$(SDK)/linux/bde \
             -I$(SDK)/bcmdrd/include

linux_ngbde-y := ngbde_main.o \
                 ngbde_kapi.o \
                 ngbde_ioctl.o \
                 ngbde_procfs.o \
                 ngbde_pio.o \
                 ngbde_iio.o \
                 ngbde_paxb.o \
                 ngbde_dma.o \
                 ngbde_intr.o \
                 ngbde_pgmem.o \
                 ngbde_pci_probe.o \
                 ngbde_iproc_probe.o \
                 ngbde_swdev.o
