# libsaithrift-dev package

LIBSAITHRIFT_DEV_P4 = libsaithrift-dev_1.0.4_amd64.deb
$(LIBSAITHRIFT_DEV_P4)_SRC_PATH = $(SRC_PATH)/sonic-sairedis/SAI
$(LIBSAITHRIFT_DEV_P4)_DEPENDS += $(LIBTHRIFT) $(LIBTHRIFT_DEV) $(THRIFT_COMPILER) $(P4_SWITCH)
$(LIBSAITHRIFT_DEV_P4)_RDEPENDS += $(LIBTHRIFT) $(P4_SWITCH)
SONIC_DPKG_DEBS += $(LIBSAITHRIFT_DEV_P4)
