# sonic broadcom one image installer

SONIC_ONE_ABOOT_IMAGE = sonic-aboot-p4.swi
$(SONIC_ONE_ABOOT_IMAGE)_MACHINE = p4
$(SONIC_ONE_ABOOT_IMAGE)_IMAGE_TYPE = aboot
$(SONIC_ONE_ABOOT_IMAGE)_INSTALLS += $(ARISTA_PLATFORM_MODULE_DRIVERS) $(ARISTA_PLATFORM_MODULE_PYTHON2) $(ARISTA_PLATFORM_MODULE_PYTHON3) $(ARISTA_PLATFORM_MODULE)

# FIXME: this is a temporary workaround for testing the platform driver
$(SONIC_ONE_ABOOT_IMAGE)_DOCKERS += docker-platform-monitor.gz
# $(SONIC_ONE_ABOOT_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_IMAGES)

SONIC_INSTALLERS += $(SONIC_ONE_ABOOT_IMAGE)
