# -*- Kbuild -*-
#
# Linux psample module.
#
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

obj-m := linux_psample.o

ccflags-y := $(LKM_CFLAGS) \
             -I$(SDK)/shr/include \
             -I$(SDK)/bcmdrd/include \
             -I$(SDK)/linux/include \
             -I$(SDK)/linux/knet/include \
             -I$(SDK)/linux/knet

linux_psample-y := psample.o
