# -*- Makefile -*-
#
# Linux psample module.
#
# $Copyright: (c) 2020 Broadcom.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

include Kbuild

ifeq ($(KERNELRELEASE),)

MOD_NAME = linux_psample

include $(SDK)/make/lkm.mk

endif

.PHONY: distclean

distclean:
